---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: svc-eureka
  name: svc-eureka
  namespace: hld
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: svc-eureka
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: svc-eureka
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: hld-configmap
          image: '47.114.1.23/hld-k8s/eureka-server:2020-11-11_17-51-03'
          imagePullPolicy: IfNotPresent
          name: eureka
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: jenkins-admin
      serviceAccountName: jenkins-admin
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/displayName: 注册中心
    k8s.kuboard.cn/workload: svc-eureka
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: svc-eureka
  name: svc-eureka
  namespace: hld
spec:
  clusterIP: 10.96.53.148
  externalTrafficPolicy: Cluster
  ports:
    - name: y2ppbp
      nodePort: 30010
      port: 30010
      protocol: TCP
      targetPort: 30010
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: svc-eureka
  sessionAffinity: None
  type: NodePort

